# Frog kitty theme
background #0d130e
foreground #ecf0e6

selection_background #2d4235
selection_foreground #ecf0e6

active_border_color #7aa050
inactive_border_color #1c2a22

active_tab_background #1a241d
active_tab_foreground #ecf0e6
inactive_tab_background #0d130e
inactive_tab_foreground #7aa050

url_color #7aa050

cursor #7aa050
cursor_text_color #0d130e

color0 #151c17
color1 #c95a4a
color2 #97a13c
color3 #ce9c1b
color4 #4a5f52
color5 #44563e
color6 #5f7a3a
color7 #c9cfc4
color8 #1d2620
color9 #d47a6a
color10 #d8be29
color11 #d8be29
color12 #a8c488
color13 #8fae94
color14 #a8c4a0
color15 #ecf0e6
