# Copper kitty theme
background #131722
foreground #f0ece8

selection_background #3a4862
selection_foreground #f0ece8

active_border_color #c08850
inactive_border_color #3a4862

active_tab_background #222940
active_tab_foreground #f0ece8
inactive_tab_background #131722
inactive_tab_foreground #c08850

url_color #c08850

cursor #c08850
cursor_text_color #131722

color0 #1a2030
color1 #d45a5a
color2 #5a8a7a
color3 #b88a70
color4 #4a5875
color5 #663837
color6 #6a9a8a
color7 #c9c5c1
color8 #222940
color9 #d4706a
color10 #8ab5a5
color11 #D9A796
color12 #6a7fa0
color13 #B38276
color14 #a5c0b5
color15 #f0ece8
