include theme.conf

# Fonts
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12

# No border colors.
window_border_width 1pt
active_border_color #467362

# Cursor
shell_integration no-cursor
cursor_shape block
cursor_underline_thickness 2
cursor_blink_interval 0.8
cursor_shape_unfocused block

# Scrollbar
scrollbar scrolled
scrollback_lines 2000

# Split window bindings
map ctrl+shift+t launch

# Navigate
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up

# Close a split
map ctrl+shift+q close_window
