# Moon kitty theme
background #141726
foreground #e2e8f4

selection_background #2d3558
selection_foreground #e2e8f4

active_border_color #7095cc
inactive_border_color #202640

active_tab_background #222840
active_tab_foreground #e2e8f4
inactive_tab_background #141726
inactive_tab_foreground #7095cc

url_color #7095cc

cursor #7095cc
cursor_text_color #141726

color0 #1b1f30
color1 #c95f5f
color2 #7a72b8
color3 #b8a45f
color4 #4a5484
color5 #374767
color6 #536498
color7 #c5ccdf
color8 #242a42
color9 #d47a7a
color10 #9c94d4
color11 #d4c488
color12 #9cb4e0
color13 #7a84ac
color14 #a8b8dc
color15 #e2e8f4
