# Frog theme

format = """
$username@$hostname\
$directory\
$git_branch\
$character
"""

right_format = "$cmd_duration$status$jobs$time"

scan_timeout = 10

[username]
format = "[$user]($style)"
style_user = "bold #7aa050"
style_root = "bold #c95a4a"
show_always = true

[hostname]
format = "[$hostname]($style):"
style = "bold #a8c488"
ssh_only = false

[directory]
format = "[ $path/ ]($style)"
style = "bold #5f7a3a"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "at [$branch(:$remote_branch) ]($style)"
style = "bold #ce9c1b"

[character]
success_symbol = "[❯](brgreen)"
error_symbol = "[❯](brred)"

[time]
disabled = false
style = "#8fa192"
format = "[$time]($style) "
time_format = "%H:%M:%S"

[cmd_duration]
min_time = 2000
style = "#7aa050"
format = "took [$duration]($style) "

[status]
disabled = false
style = "#c95a4a"
format = "[$symbol $maybe_status]($style) "

[jobs]
threshold = 1
symbol = "⚙ "
style = "#7aa050"
format = "[$number$symbol]($style)"
