# Mirror theme

format = """
$username@$hostname\
$directory\
$git_branch\
$character
"""

right_format = "$cmd_duration$status$jobs$time"

scan_timeout = 10

[username]
format = "[$user]($style)"
style_user = "bold #b39a5f"
style_root = "bold #b85a4a"
show_always = true

[hostname]
format = "[$hostname]($style):"
style = "bold #c9b68a"
ssh_only = false

[directory]
format = "[ $path/ ]($style)"
style = "bold #8f7a4a"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "at [$branch(:$remote_branch) ]($style)"
style = "bold #8a8f66"

[character]
success_symbol = "[❯](bryellow)"
error_symbol = "[❯](brred)"

[time]
disabled = false
style = "#92896e"
format = "[$time]($style) "
time_format = "%H:%M:%S"

[cmd_duration]
min_time = 2000
style = "#b39a5f"
format = "took [$duration]($style) "

[status]
disabled = false
style = "#b85a4a"
format = "[$symbol $maybe_status]($style) "

[jobs]
threshold = 1
symbol = "⚙ "
style = "#b39a5f"
format = "[$number$symbol]($style)"
