# Copper theme

format = """
$username@$hostname\
$directory\
$git_branch\
$character
"""

right_format = "$cmd_duration$status$jobs$time"

scan_timeout = 10

[username]
format = "[$user]($style)"
style_user = "bold #401317"
style_root = "bold #d45a5a"
show_always = true

[hostname]
format = "[$hostname]($style):"
style = "bold #8D5D57"
ssh_only = false

[directory]
format = "[ $path/ ]($style)"
style = "bold #c08850"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "at [$branch(:$remote_branch) ]($style)"
style = "bold #D9A796"

[character]
success_symbol = "[❯](brblue)"
error_symbol = "[❯](brred)"

[time]
disabled = false
style = "#8a95a7"
format = "[$time]($style) "
time_format = "%H:%M:%S"

[cmd_duration]
min_time = 2000
style = "#b88a70"
format = "took [$duration]($style) "

[status]
disabled = false
style = "#d45a5a"
format = "[$symbol $maybe_status]($style) "

[jobs]
threshold = 1
symbol = "⚙ "
style = "#c08850"
format = "[$number$symbol]($style)"
