# Graffiti kitty theme
background #141a1b
foreground #e3ebe6

selection_background #315d56
selection_foreground #e3ebe6

active_border_color #cb58be
inactive_border_color #26302f

active_tab_background #1d2728
active_tab_foreground #e3ebe6
inactive_tab_background #141a1b
inactive_tab_foreground #59c2a5

url_color #59c2a5

cursor #cb58be
cursor_text_color #141a1b

color0 #1d2728
color1 #b85a66
color2 #4ca658
color3 #c6c354
color4 #5f6498
color5 #cb58be
color6 #59c2a5
color7 #b2c9ba
color8 #344341
color9 #cc6f74
color10 #6cc178
color11 #d9d676
color12 #7b7fb5
color13 #de7ad3
color14 #6edfe2
color15 #e3ebe6
