-- Variables

--# Applications
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "kitty"
local fileManager = "nautilus"
local applauncher = "rofi -show drun"

--# Modifiers
local mainMod = "SUPER"
local swapMod = "SUPER + ALT"
local screenChangeMod = "SUPER + SHIFT"
local workspaceMod = "SUPER + CTRL"

-- General

--# Resize windows from edges

hl.bind(mainMod .. " + F11", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind(mainMod .. " + F10", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind(mainMod .. " + ALT + F10", hl.dsp.exec_cmd("wpctl set-mute, @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(mainMod .. " + F9", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("hyprshot -m region"))

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd(applauncher))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("hyprpicker -a"))

hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("loginctl lock-session"))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())

hl.bind(swapMod .. " + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(swapMod .. " + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(swapMod .. " + down", hl.dsp.window.swap({ direction = "d" }))
hl.bind(swapMod .. " + up", hl.dsp.window.swap({ direction = "u" }))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))

hl.bind(screenChangeMod .. " + left", hl.dsp.window.move({ monitor = "l" }))
hl.bind(screenChangeMod .. " + right", hl.dsp.window.move({ monitor = "r" }))

hl.bind("F11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(workspaceMod .. " + left", hl.dsp.focus({ workspace = "m-1" }))
hl.bind(workspaceMod .. " + right", hl.dsp.focus({ workspace = "m+1" }))

hl.bind(workspaceMod .. " + W", hl.dsp.exec_cmd("bash -c 'NEW_WS=$(hyprctl workspaces -j | jq \"[.[].id] | max + 1\"); hyprctl dispatch workspace \"$NEW_WS\"; hyprctl keyword workspace \"$NEW_WS, persistent:true\"'"))
hl.bind(workspaceMod .. " + R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mainMod .. " + SHIFT + S", hl.dsp.global("quickshell:togglePopoutSliderMenu"))

hl.bind(mainMod .. " + SHIFT + R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()

    hl.bind("A", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("D", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("S", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("W", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })

    hl.bind("left", hl.dsp.focus({ direction = "left" }))
    hl.bind("right", hl.dsp.focus({ direction = "right" }))
    hl.bind("down", hl.dsp.focus({ direction = "down" }))
    hl.bind("up", hl.dsp.focus({ direction = "up" }))

    hl.bind("R", hl.dsp.submap("reset"))
end)

hl.monitor({
    output = "DP-9",
    mode = "2560x1440@59.951",
    position = "-1152x0",
    scale = "1.25",
    transform = 1,
})

hl.monitor({
    output = "DP-11",
    mode = "2560x1440@59.951",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "eDP-1",
    mode = "2880x1920@120",
    position = "2560x0",
    scale = "2",
})

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    monitor = "DP-11",
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-11",
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "DP-9",
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "DP-9",
    persistent = true,
})

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

-- TODO: manual review — unknown section 'animation {' on line 220
hl.config({
    general = {
        resize_on_border = true,
        extend_border_grab_area = 15,
        hover_icon_on_border = true,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(1a0933ff)", "rgba(3730a3ff)", "rgba(0e7490ff)", "rgba(047857ff)", "rgba(22c55eff)" }, angle = 45 },
            inactive_border = "rgba(1c1d1faa)",
        },
        gaps_out = 8,
        gaps_in = 4,
    },
    input = {
        touchpad = {
            natural_scroll = true,
        },
    },
    -- Cursor
    cursor = {
        inactive_timeout = 3,
        hide_on_key_press = true,
    },
    -- Decoration
    decoration = {
        rounding = 5,
        border_part_of_window = true,
        inactive_opacity = 0.9,
        active_opacity = 1,
        dim_inactive = true,
        dim_strength = 0.15,
    },
})

-- Curves
hl.curve( "switch", { type = "bezier", points = { {0.31, -0.43}, {0.53, 1.03} } } )
hl.curve( "smooth", { type = "bezier", points = { {0.83, 0.44}, {0.34, 0.87} } } )

-- Animations
hl.animation( { leaf = "workspaces", enabled = true, speed = 7.5, bezier = "switch" } )
hl.animation( { leaf = "windowsMove", enabled = true, speed = 3, bezier = "smooth" } )
hl.animation( { leaf = "windowsIn", enabled = true, speed = 4, bezier = "smooth", style = "popin 10%" } )
hl.animation( { leaf = "windowsOut", enabled = true, speed = 4, bezier = "smooth", style = "popin 10%" } )

-- On start
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("swaync")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("protonvpn-app")
end)