# Variables

$terminal = kitty
$fileManager = nautilus
$applauncher = wofi -i --show drun --allow-images -D key_expand=Tab
$mainMod = SUPER


# Keybindings

bind = , PRINT, exec, hyprshot -m region # Screenshots

bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive, 
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, M, exec, $applauncher

bindm = $mainMod, mouse:272, movewindow


# Monitors

monitor=DP-9,2560x1440@59.951,-1152x0,1.25,transform,1
monitor=DP-11,2560x1440@59.951,0x0,1.25
monitor=eDP-1,2880x1920@120,2048x0,2.13


# Windows & Workspaces

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}


# Start on launch

exec-once = hyprpaper
exec-once = dunst
exec-once = systemctl --user start hyprpolkitagent
exec-once = protonvpn-app


# Environment variables

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
