# Emerald theme

wallpaper {
	monitor = eDP-1
	path = $HOME/.config/themes/emerald/wallpapers/emerald_2880x1920.png
	fit_mode = cover
}

wallpaper {
	monitor = DP-11
	path = $HOME/.config/themes/emerald/wallpapers/emerald_2560x1440.png
	fit_mode = cover
}

wallpaper {
	monitor = DP-9
	path = $HOME/.config/themes/emerald/wallpapers/emerald_1440x2560.png
	fit_mode = cover
}

splash = false
ipc = off