wallpaper {
	monitor = eDP-1
	path = $HOME/wallpapers/images/arch.png
	fit_mode = cover
}

wallpaper {
	monitor = DP-11
	path = $HOME/wallpapers/images/arch.png
	fit_mode = cover
}

wallpaper {
	monitor = DP-9
	path = $HOME/wallpapers/images/arch.png
	fit_mode = cover
}

splash = false
ipc = off
