wallpaper {
	monitor = eDP-1
	path = $HOME/dotfiles/wallpapers/blindfold-edp1.png
	fit_mode = cover
}

wallpaper {
	monitor = DP-11
	path = $HOME/dotfiles/wallpapers/blindfold-edp1.png	
	fit_mode = cover
}

wallpaper {
	monitor = DP-9
	path = $HOME/dotfiles/wallpapers/blindfold-dp9.png
	fit_mode = cover
}

splash = false
ipc = off
