-- Copper theme

local M = {}

M.colors = {
	bg = "#131722",
	widget = "#e8e4e0",
	border = "#3a4862",
	textMuted = "#8a95a7",
	text = "#f0ece8",
	accent = "#c08850",
	warn = "#b88a70",
	notify = "#d45a5a",
	positive = "#5a8a7a",
	gradient1 = "#401317",
	gradient2 = "#663837",
	gradient3 = "#8D5D57",
	gradient4 = "#B38276",
	gradient5 = "#D9A796",

	bgDark = "#0d1018",
	bgDarker = "#0a0d14",
	surface = "#1a2030",
	surfaceBright = "#222940",
	borderBright = "#4a5875",
	textDim = "#c9c5c1",
	textMutedBright = "#9aa5b7",
	positiveBright = "#6a9a8a",
	notifyDark = "#b04a4a",
	accentSoft = "#D9A796",
}

M.lualine = {
	normal = {
		a = { bg = M.colors.accent, fg = M.colors.bg, gui = "bold" },
		b = { bg = M.colors.surfaceBright, fg = M.colors.text },
		c = { bg = M.colors.bg, fg = M.colors.textMuted },
	},
	insert = {
		a = { bg = M.colors.positive, fg = M.colors.bg, gui = "bold" },
		b = { bg = M.colors.surfaceBright, fg = M.colors.text },
		c = { bg = M.colors.bg, fg = M.colors.textMuted },
	},
	visual = {
		a = { bg = M.colors.warn, fg = M.colors.bg, gui = "bold" },
		b = { bg = M.colors.surfaceBright, fg = M.colors.text },
		c = { bg = M.colors.bg, fg = M.colors.textMuted },
	},
	replace = {
		a = { bg = M.colors.notify, fg = M.colors.bg, gui = "bold" },
		b = { bg = M.colors.surfaceBright, fg = M.colors.text },
		c = { bg = M.colors.bg, fg = M.colors.textMuted },
	},
	command = {
		a = { bg = M.colors.accentSoft, fg = M.colors.bg, gui = "bold" },
		b = { bg = M.colors.surfaceBright, fg = M.colors.text },
		c = { bg = M.colors.bg, fg = M.colors.textMuted },
	},
	inactive = {
		a = { bg = M.colors.bg, fg = M.colors.textMuted },
		b = { bg = M.colors.bg, fg = M.colors.textMuted },
		c = { bg = M.colors.bg, fg = M.colors.textMuted },
	},
}

local c = M.colors

local highlights = {
	Normal = { fg = c.text, bg = c.bg },
	NormalNC = { fg = c.text, bg = c.bg },
	NormalFloat = { fg = c.text, bg = c.bgDark },
	FloatBorder = { fg = c.border, bg = c.bgDark },
	FloatTitle = { fg = c.accent, bg = c.bgDark, bold = true },
	WinSeparator = { fg = c.border },
	VertSplit = { fg = c.border },
	MsgSeparator = { fg = c.border },
	StatusLine = { fg = c.text, bg = c.surfaceBright },
	StatusLineNC = { fg = c.textMuted, bg = c.bg },
	TabLine = { fg = c.textMuted, bg = c.surfaceBright },
	TabLineFill = { fg = c.text, bg = c.bg },
	TabLineSel = { fg = c.accent, bg = c.surfaceBright, bold = true },
	WinBar = { fg = c.text, bg = c.bg },
	WinBarNC = { fg = c.textMuted, bg = c.bg },
	Cursor = { fg = c.bg, bg = c.accent },
	CursorLine = { bg = c.surface },
	CursorColumn = { bg = c.surface },
	ColorColumn = { bg = c.surface },
	LineNr = { fg = c.borderBright },
	CursorLineNr = { fg = c.accent, bold = true },
	SignColumn = { fg = c.text, bg = c.bg },
	Folded = { fg = c.textMuted, bg = c.surface },
	FoldColumn = { fg = c.borderBright },
	NonText = { fg = c.borderBright },
	EndOfBuffer = { fg = c.bgDarker },
	Conceal = { fg = c.textMutedBright },
	SpecialKey = { fg = c.textMutedBright },
	Visual = { bg = c.border },
	VisualNOS = { bg = c.surfaceBright },
	Pmenu = { fg = c.text, bg = c.surfaceBright },
	PmenuSel = { fg = c.bg, bg = c.accent },
	PmenuSbar = { bg = c.surface },
	PmenuThumb = { bg = c.borderBright },
	PmenuMatch = { fg = c.accentSoft, bold = true },
	WildMenu = { fg = c.bg, bg = c.accent },
	Search = { fg = c.bg, bg = c.accent },
	IncSearch = { fg = c.bg, bg = c.accentSoft },
	CurSearch = { fg = c.bg, bg = c.accentSoft },
	Substitute = { fg = c.bg, bg = c.notify },
	MatchParen = { bg = c.border, bold = true },
	Directory = { fg = c.accent, bold = true },
	Title = { fg = c.accent, bold = true },
	Question = { fg = c.accent, bold = true },
	ModeMsg = { fg = c.textMuted },
	MoreMsg = { fg = c.accent },
	MsgArea = { fg = c.text },
	WarningMsg = { fg = c.warn },
	ErrorMsg = { fg = c.notify, bold = true },
	QuickFixLine = { bg = c.surface },
	SpellBad = { sp = c.notify, undercurl = true },
	SpellCap = { sp = c.warn, undercurl = true },
	SpellLocal = { sp = c.accent, undercurl = true },
	SpellRare = { sp = c.positiveBright, undercurl = true },

	Comment = { fg = c.textMuted, italic = true },
	Constant = { fg = c.accentSoft },
	String = { fg = c.positive },
	Character = { fg = c.positive },
	Number = { fg = c.accentSoft },
	Boolean = { fg = c.accentSoft },
	Float = { fg = c.accentSoft },
	Identifier = { fg = c.text },
	Function = { fg = c.accent },
	Statement = { fg = c.gradient3 },
	Conditional = { fg = c.gradient3 },
	Repeat = { fg = c.gradient3 },
	Label = { fg = c.gradient3 },
	Operator = { fg = c.accentSoft },
	Keyword = { fg = c.gradient3 },
	Exception = { fg = c.notify },
	PreProc = { fg = c.gradient3 },
	Include = { fg = c.accent },
	Define = { fg = c.gradient3 },
	Macro = { fg = c.accentSoft },
	PreCondit = { fg = c.gradient3 },
	Type = { fg = c.warn },
	StorageClass = { fg = c.warn },
	Structure = { fg = c.warn },
	Typedef = { fg = c.warn },
	Special = { fg = c.accentSoft },
	SpecialChar = { fg = c.accentSoft },
	Tag = { fg = c.accent },
	Delimiter = { fg = c.textMutedBright },
	SpecialComment = { fg = c.textMuted },
	Debug = { fg = c.notify },
	Underlined = { underline = true },
	Ignore = { fg = c.border },
	Error = { fg = c.notify },
	Todo = { fg = c.warn, bold = true },

	DiagnosticError = { fg = c.notify },
	DiagnosticWarn = { fg = c.warn },
	DiagnosticInfo = { fg = c.accent },
	DiagnosticHint = { fg = c.positiveBright },
	DiagnosticVirtualTextError = { fg = c.notify },
	DiagnosticVirtualTextWarn = { fg = c.warn },
	DiagnosticVirtualTextInfo = { fg = c.accent },
	DiagnosticVirtualTextHint = { fg = c.positiveBright },
	DiagnosticUnderlineError = { sp = c.notify, undercurl = true },
	DiagnosticUnderlineWarn = { sp = c.warn, undercurl = true },
	DiagnosticUnderlineInfo = { sp = c.accent, undercurl = true },
	DiagnosticUnderlineHint = { sp = c.positiveBright, undercurl = true },
	LspReferenceText = { bg = c.surface },
	LspReferenceWrite = { bg = c.surface },
	LspReferenceRead = { bg = c.surface },

	BlinkCmpMenu = { fg = c.text, bg = c.surfaceBright },
	BlinkCmpMenuBorder = { fg = c.border, bg = c.surfaceBright },
	BlinkCmpMatch = { fg = c.accentSoft, bold = true },
	BlinkCmpDoc = { fg = c.text, bg = c.bgDark },
	BlinkCmpDocBorder = { fg = c.border, bg = c.bgDark },

	TelescopeNormal = { fg = c.text, bg = c.bg },
	TelescopeBorder = { fg = c.border, bg = c.bg },
	TelescopePromptTitle = { fg = c.bg, bg = c.accent },
	TelescopeResultsTitle = { fg = c.bg, bg = c.accent },
	TelescopePreviewTitle = { fg = c.bg, bg = c.accent },
	TelescopeSelection = { fg = c.text, bg = c.surface, bold = true },
	TelescopeMatching = { fg = c.accentSoft, bold = true },
	TelescopePromptPrefix = { fg = c.accent },

	NeoTreeNormal = { fg = c.text, bg = c.bg },
	NeoTreeNormalNC = { fg = c.text, bg = c.bg },
	NeoTreeRootName = { fg = c.accent, bold = true },
	NeoTreeDirectoryName = { fg = c.text },
	NeoTreeDirectoryIcon = { fg = c.accent },
	NeoTreeIndentMarker = { fg = c.border },
	NeoTreeDotFile = { fg = c.textMutedBright },
	NeoTreeFileNameOpened = { fg = c.text, bold = true },
	NeoTreeGitModified = { fg = c.warn },
	NeoTreeGitAdded = { fg = c.positive },
	NeoTreeGitDeleted = { fg = c.notify },
	NeoTreeGitUntracked = { fg = c.positiveBright },

	AlphaHeader = { fg = c.accent },
	AlphaButtons = { fg = c.gradient3 },
	AlphaShortcut = { fg = c.accentSoft },
	AlphaFooter = { fg = c.textMuted },
}

function M.apply()
	vim.opt.termguicolors = true

	for group, opts in pairs(highlights) do
		vim.api.nvim_set_hl(0, group, opts)
	end
end

return M
