# Moon theme

format = """
$username@$hostname\
$directory\
$git_branch\
$character
"""

right_format = "$cmd_duration$status$jobs$time"

scan_timeout = 10

[username]
format = "[$user]($style)"
style_user = "bold #7095cc"
style_root = "bold #c95f5f"
show_always = true

[hostname]
format = "[$hostname]($style):"
style = "bold #9cb4e0"
ssh_only = false

[directory]
format = "[ $path/ ]($style)"
style = "bold #536498"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "at [$branch(:$remote_branch) ]($style)"
style = "bold #7a72b8"

[character]
success_symbol = "[❯](brblue)"
error_symbol = "[❯](brred)"

[time]
disabled = false
style = "#8a94b8"
format = "[$time]($style) "
time_format = "%H:%M:%S"

[cmd_duration]
min_time = 2000
style = "#7095cc"
format = "took [$duration]($style) "

[status]
disabled = false
style = "#c95f5f"
format = "[$symbol $maybe_status]($style) "

[jobs]
threshold = 1
symbol = "⚙ "
style = "#7095cc"
format = "[$number$symbol]($style)"
