# Blindfold kitty theme
background #0e1219
foreground #f0ece8

selection_background #2d3550
selection_foreground #f0ece8

active_border_color #7a9ab8
inactive_border_color #1c2440

active_tab_background #1a1e2e
active_tab_foreground #f0ece8
inactive_tab_background #0e1219
inactive_tab_foreground #7a9ab8

url_color #7a9ab8

cursor #7a9ab8
cursor_text_color #0e1219

color0 #151a26
color1 #d45a5a
color2 #a85a5a
color3 #b88a70
color4 #4a5875
color5 #445668
color6 #5f7890
color7 #c9c5c1
color8 #1d2333
color9 #d67575
color10 #c47a7a
color11 #d0a488
color12 #9cb4cc
color13 #8a94b8
color14 #a0b8cc
color15 #f0ece8
