# Background, frog theme
background {
    monitor = eDP-1
    color = rgba(0, 0, 0, 1)
    path = $HOME/.config/themes/frog/wallpapers/frog_1_2880x1920.png
}

background {
    monitor = DP-11
    color = rgba(0, 0, 0, 1)
    path = $HOME/.config/themes/frog/wallpapers/frog_1_2560x1440.png
}

background {
    monitor = DP-9
    color = rgba(0, 0, 0, 1)
}

input-field {
    monitor = eDP-1
    size = 300, 50
    position = 0, -40

    halign = center
    valign = center

    outline_thickness = 2
    rounding = 6
    placeholder_text = <i>Password...</i>

    inner_color = rgba(0, 0, 0, 0.5)
    outer_color = rgba(7aa050ff) rgba(5f7a3aff) rgba(44563eff) rgba(293428ff) rgba(0d130eff) 45deg
    font_color = rgb(236, 240, 230)

    fade_on_empty = true

    fail_color = rgb(201, 90, 74)
    fail_text = <i>$ATTEMPTS failed attempts</i>
}

label {
    monitor   = eDP-1
    text      = $TIME
    color     = rgba(236, 240, 230, 1)

    font_size = 72
    font_family = JetBrainsMono Nerd Font

    position  = 0, 150
    halign    = center
    valign    = center
}

label {
    monitor   = eDP-1
    text      = Welcome back $USER
    color     = rgba(236, 240, 230, 1.0)
    font_size = 20

    position  = 0, 80
    halign    = center
    valign    = center
}

input-field {
    monitor = DP-11
    size = 300, 50
    position = 0, -40

    halign = center
    valign = center

    outline_thickness = 2
    rounding = 6
    placeholder_text = <i>Password...</i>

    inner_color = rgba(0, 0, 0, 0.5)
    outer_color = rgba(7aa050ff) rgba(5f7a3aff) rgba(44563eff) rgba(293428ff) rgba(0d130eff) 45deg
    font_color = rgb(236, 240, 230)

    fade_on_empty = true

    fail_color = rgb(201, 90, 74)
    fail_text = <i>$ATTEMPTS failed attempts</i>
}

label {
    monitor   = DP-11
    text      = $TIME
    color     = rgba(236, 240, 230, 1)

    font_size = 72
    font_family = JetBrainsMono Nerd Font

    position  = 0, 150
    halign    = center
    valign    = center
}

label {
    monitor   = DP-11
    text      = Welcome back $USER
    color     = rgba(236, 240, 230, 1.0)
    font_size = 20

    position  = 0, 80
    halign    = center
    valign    = center
}
