# City kitty theme
background #131415
foreground #EBE7D7

selection_background #38484C
selection_foreground #EBE7D7

active_border_color #C99F75
inactive_border_color #38484C

active_tab_background #2C3133
active_tab_foreground #EBE7D7
inactive_tab_background #131415
inactive_tab_foreground #C99F75

url_color #C99F75

cursor #C99F75
cursor_text_color #131415

color0 #1B1E22
color1 #9B3E4B
color2 #556755
color3 #A39A74
color4 #3E5E83
color5 #735067
color6 #57686C
color7 #8E8D74
color8 #2C3133
color9 #B85660
color10 #718856
color11 #C89C75
color12 #697786
color13 #A56B90
color14 #748990
color15 #EBE7D7
